### ISSUE TITLE
Installer stops at Solr installation

### ISSUE THREAD

**Issue by olychron** [structureddynamics/Open-Semantic-Framework-Installer#13] opened 2016-04-09 22:27 UTC
The URL to get the apache-solr-3.6.1.tgz file is invalid. Looks like it has moved. Any instruction for getting around this?

**Comment by fgiasson** [comment] 2016-04-11 13:44
Hi @olychron,

The address is: http://archive.apache.org/dist/lucene/solr/3.6.0/apache-solr-3.6.0.tgz

for each supported Linux distribution. I just tested it and it is reachable from here. Maybe it was just a network issue on your side, could you re-try please?

**Comment by olychron** [comment] 2016-04-11 22:50
Thank your for your reply.

I ran the script again and this part completed without issue. You're
probably correct about the network issue. However, many other errors
followed. I started over with a clean Ubuntu install and the script ran
without error until the very end. The PHPUnit is now asking for PHP5.6 and
won't run the final tests. OSF for Drupal can't find drush, so the script
really doesn't start. Not sure if these two things are related.

On Mon, Apr 11, 2016 at 6:44 AM, Frederick Giasson <notifications@github.com

**Comment by fgiasson** [comment] 2016-04-12 13:19
What is the Linux distribution you are trying to run the OSF Installer on, and what is the exact version?

**Comment by olychron** [comment] 2016-04-12 14:34
Ubuntu 14.04, basic server only. I wasn't able to run the PHPUnit test, due
to PHP5.6 requirement. After manually installing Drush I was able to kick
off the OSF for Drupal installation and all went well. Thank you and if I
can provide any other info let me know.

On Tue, Apr 12, 2016 at 6:19 AM, Frederick Giasson <notifications@github.com

**Comment by fgiasson** [comment] 2016-04-14 12:55
Thanks for reporting, I will retest to see if I can reproduce this issue.

**Comment by fgiasson** [comment] 2016-04-14 16:24
I just tested the whole OSF installer process and everything works fine from here on latest Ubuntu 14.04. Will close this ticket until we get more information/reproducability for this issue.

**Closed as completed by fgiasson** 2016-04-14 16:24 UTC

**Comment by fgiasson** [comment] 2016-04-20 17:55
@olychron we found a bug related to the Drush installation. Please retry with the latest OSF Installer, one of the Drush path changed since the last version and I think that was the cause of your issue.

You may want to check the OSF mailing list for more information.

**Comment by olychron** [comment] 2016-04-22 16:52
Hi Frederick,

I'm still getting errors when the PHPUnit tries to test the OSF install.
Also, still seeing error at Drush install. Attaching the logs for more info.

-Olivia

**Comment by olychron** [comment] 2016-04-22 17:14
Frederick,

I installed Drush using the _sudo apt-get install drush_ command and
updated it using _sudo drush dl drush --destination='/usr/share'_. I
selected the latest version.

Then i reran the installer for Drupal. I get these errors:

Create Drupal roles for OSF Drupal...
The drush command 'role-create contributor' could not be found.  Run
[error]
`drush cache-clear drush` to clear the commandfile cache if you have
installed new extensions.
The drush command 'role-create owner/curator' could not be found.    [error]
Run `drush cache-clear drush` to clear the commandfile cache if you
have installed new extensions.

I guess this is why i've been running into permissions issues in my other
installation efforts.

-Olivia

**Comment by fgiasson** [comment] 2016-05-10 00:44
@olychron I think you are not installating the right version of Drush. Are you installing the one for Drupal 7? This is the one that should work, and this is probably the reason why you are getting these commands not found errors.
